version: "3.8"
services:
  mongo:
    image: geppettotest/mongo-local:april2020
    container_name: mongo-3319
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - gepticketsystem_3319-volume:/data/db
    ports:
      - "27018:27017"
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u root -p root --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  camunda:
    image: geppettodistribution/camunda-local:Jan2021
    container_name: camunda-3319
    ports:
      - "0000:8080"

  authproxy:
    build: ../../../application/services/default_services/authproxy
    image: authproxy-3319
    container_name: authproxy-3319
    ports:
      - "0000:8001"
    env_file: .env
    depends_on:
      - mongo
      - camunda

  securitymanager:
    build: ../../../application/services/default_services/securitymanager
    image: securitymanager-3319
    container_name: securitymanager-3319
    ports:
      - "8003:8003"
    env_file: .env
    depends_on:
      - mongo
      - camunda

  camundaservice:
    build: ../../../application/services/default_services/camunda
    image: camundaservice-3319
    container_name: camundasvc-3319
    ports:
      - "8002:8002"
    env_file: .env
    depends_on:
      - mongo
      - camunda
      - securitymanager

  apigateway:
    build: ../../../application/services/custom_services/apigateway
    image: apigateway-3319
    container_name: apigateway-3319
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - camunda
      - camundaservice
      - authproxy
      - securitymanager
      - tickets
      - servicetypes
      - severity



  tickets: 
    build: ../../../application/services/custom_services/tickets
    image: tickets-3319
    container_name: tickets-3319
    ports: 
      - 8012:8012
    env_file: .env
    depends_on:
      - mongo

  servicetypes: 
    build: ../../../application/services/custom_services/servicetypes
    image: servicetypes-3319
    container_name: servicetypes-3319
    ports: 
      - 8013:8013
    env_file: .env
    depends_on:
      - mongo

  severity: 
    build: ../../../application/services/custom_services/severity
    image: severity-3319
    container_name: severity-3319
    ports: 
      - 8014:8014
    env_file: .env
    depends_on:
      - mongo


volumes:
  gepticketsystem_3319-volume:
    driver: local
